In [1]:
import numpy as np
import matplotlib.pyplot as plt
import qutip as qt
import pyqosc as qo
import scipy as sp

In [4]:
N = 20
vdp = qo.vdp(N=N, omega = 1, gamma_1 = 2, gamma_2 = 0.1)
rho_0 = qt.coherent_dm(vdp.N, 15+20j)
tau = 2

vdp.shortcut(rho_0, tau, trajectory_func = 0, err_tol_b = 1e-3, timepoints = 101, special = "linear_impens",
                 maxiter = 100, report = True, plot_resulting_trajectory = False, save_to_osc = False,
                 dy = 0)

== Shortcut finished == 

Result obtained with 13 iterations. 

Specifications: 
   Method: Impens2023 
   tau = 2 

Calculated metrics: 
   b_tau - b_ss = (0.0005412961345951373+0.000825809629161049j) 
   d_tr(rho_tau, rho_ss) = 0.3719639745008652 
   Omega_1_avg = 1.3069460092164857
   Omega_2_avg = 0.8824618207964462



(array([-1.46709025, -1.46397766, -1.46086143, -1.45774159, -1.45461817,
        -1.45149123, -1.44836078, -1.44522687, -1.44208953, -1.4389488 ,
        -1.43580471, -1.43265731, -1.42950663, -1.42635271, -1.42319558,
        -1.42003528, -1.41687184, -1.41370531, -1.41053573, -1.40736312,
        -1.40418753, -1.40100899, -1.39782755, -1.39464323, -1.39145608,
        -1.38826613, -1.38507343, -1.381878  , -1.3786799 , -1.37547914,
        -1.37227578, -1.36906985, -1.36586138, -1.36265043, -1.35943701,
        -1.35622118, -1.35300296, -1.34978241, -1.34655954, -1.34333441,
        -1.34010705, -1.3368775 , -1.3336458 , -1.33041198, -1.32717608,
        -1.32393813, -1.32069819, -1.31745628, -1.31421245, -1.31096672,
        -1.30771914, -1.30446975, -1.30121858, -1.29796567, -1.29471106,
        -1.29145478, -1.28819688, -1.28493738, -1.28167634, -1.27841378,
        -1.27514974, -1.27188426, -1.26861737, -1.26534912, -1.26207954,
        -1.25880866, -1.25553653, -1.25226318, -1.2

In [3]:
N = 20
vdp = qo.vdp(N=N, omega = 1, gamma_1 = 2, gamma_2 = 0.1, Omega_2 = 2)
rho_0 = qt.coherent_dm(vdp.N, 15+20j)
tau = 2

vdp.shortcut(rho_0, tau, trajectory_func = 0, err_tol_b = 1e-6, timepoints = 101, special = "hyperbolic_spiral",
                 maxiter = 100, report = True, plot_resulting_trajectory = False, save_to_osc = False,
                 dy = 0)

== Shortcut finished == 

Result obtained with 13 iterations. 

Specifications: 
   Method: Impens2023 
   tau = 2 

Calculated metrics: 
   b_tau - b_ss = (-4.335101439489897e-07+4.3873786470180476e-09j) 
   d_tr(rho_tau, rho_ss) = 0.287939027524679 
   Omega_1_avg = 1.81297383660032
   Omega_2_avg = 1.8553599618731422



(array([-0.75021553, -0.89290205, -1.14839819, -1.38590945, -1.60653188,
        -1.81121817, -2.00080144, -2.17601487, -2.33750791, -2.48585998,
        -2.62159175, -2.74517475, -2.85703945, -2.95758208, -3.04717043,
        -3.12614882, -3.19484222, -3.25355992, -3.30259854, -3.34224465,
        -3.37277701, -3.39446842, -3.40758738, -3.4123994 , -3.40916818,
        -3.39815652, -3.37962714, -3.35384328, -3.32106926, -3.28157081,
        -3.23561542, -3.18347252, -3.12541357, -3.06171218, -2.99264401,
        -2.91848681, -2.83952017, -2.75602547, -2.6682856 , -2.57658474,
        -2.48120812, -2.38244164, -2.28057163, -2.17588446, -2.06866616,
        -1.95920208, -1.84777648, -1.73467211, -1.62016984, -1.50454818,
        -1.38808294, -1.27104673, -1.1537086 , -1.03633357, -0.91918225,
        -0.80251039, -0.68656852, -0.57160152, -0.45784821, -0.34554105,
        -0.23490567, -0.1261606 , -0.01951687,  0.08482228,  0.18666172,
         0.28581474,  0.3821033 ,  0.47535832,  0.5

In [5]:
N = 20
vdp = qo.vdp(N=N, omega = 1, gamma_1 = 2, gamma_2 = 0.1, Omega_2 = 10)
rho_0 = qt.coherent_dm(vdp.N, 15+20j)
tau = 2

vdp.shortcut(rho_0, tau, trajectory_func = 0, err_tol_b = 1e-6, timepoints = 101, special = "hyperbolic_spiral",
                 maxiter = 100, report = True, plot_resulting_trajectory = False, save_to_osc = False,
                 dy = 0)

== Shortcut finished == 

Result obtained with 12 iterations. 

Specifications: 
   Method: Impens2023 
   tau = 2 

Calculated metrics: 
   b_tau - b_ss = (-4.830024037949521e-07+2.143736990457834e-07j) 
   d_tr(rho_tau, rho_ss) = 0.3169411801818536 
   Omega_1_avg = 2.0549585314711636
   Omega_2_avg = 2.1453153259274207



(array([ 0.13519094, -0.03254937, -0.33023938, -0.61513233, -0.88730928,
        -1.1468406 , -1.39378925, -1.6282136 , -1.85016996, -2.05971478,
        -2.2569066 , -2.44180775, -2.61448588, -2.7750153 , -2.92347803,
        -3.05996491, -3.18457635, -3.2974231 , -3.39862685, -3.48832069,
        -3.56664952, -3.63377036, -3.68985254, -3.73507781, -3.76964045,
        -3.79374721, -3.80761722, -3.8114819 , -3.8055847 , -3.79018088,
        -3.76553719, -3.73193154, -3.68965257, -3.63899926, -3.58028041,
        -3.51381418, -3.43992749, -3.35895553, -3.27124108, -3.17713394,
        -3.07699029, -2.97117199, -2.86004595, -2.74398337, -2.62335911,
        -2.4985509 , -2.36993867, -2.23790378, -2.10282831, -1.96509431,
        -1.82508305, -1.68317432, -1.53974566, -1.39517165, -1.24982321,
        -1.10406687, -0.95826408, -0.81277053, -0.66793549, -0.52410113,
        -0.38160194, -0.24076405, -0.1019047 ,  0.03466838,  0.16865747,
         0.29977545,  0.4277462 ,  0.55230515,  0.6